version: "3"
services:
  back-server:
    build:
      context: ./back-end
    volumes:
      - ./front-end:/front-end
    environment:
      DB_USER: /run/secrets/db_user
      DB_PASS: /run/secrets/db_password
    depends_on:
      - db
    networks:
      - backend
      - frontend
    secrets:
      - db_user
      - db_password

  adminer:
    image: adminer
    depends_on:
      - db
      - back-server # Чтобы порядок IP не менялся
    restart: always
    networks:
      - backend
      - frontend

  db:
    image: postgres:16-alpine
    environment: 
      POSTGRES_USER: /run/secrets/db_user
      POSTGRES_PASSWORD: /run/secrets/db_password
      PGDATA: /var/lib/postgresql/data
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    expose:
      - '5432'
    restart: always
    user: 961:961
    networks:
      - backend
      - frontend
    secrets: 
      - db_user
      - db_password


networks:
  frontend:
    name: proxy_proxy
    external: true
  backend:

secrets:
  db_password:
    file: secrets/db-password.txt
  db_user:
    file: secrets/db-user.txt