version: '3'
services:
  proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "81:8080"
      - "82:5000"
    volumes:
      - /var/run/docker.sock:/tml/docker.so:ro
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
